name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '12 */6 * * *'
  watch:
    types: [started]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  PullInfomation:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: upgrade
        run: |
          sudo apt update -y
          sudo apt upgrade -y
      # Runs a set of commands using the runners shell
      - name: Install neofetch & fetch
        run: |
          sudo apt install neofetch -y
          neofetch
      
      - name: Done
        run: echo "done!"
  Deploy:
      runs-on: ubuntu-latest
      
      steps: 
        - uses: actions/checkout@v2
        
        - name: clone
          run: |
            cd ${{ github.workspace }}
            git clone https://github.com/spencerwooo/onedrive-vercel-index.git
            
        - name: edit
          run: |
            cd onedrive-vercel-index/config
            rm api.json
            rm site.json
            wget https://raw.githubusercontent.com/York618/my-pan/main/config/api.json
            wget https://raw.githubusercontent.com/York618/my-pan/main/config/site.json
            
        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: ${{ github.ref }}
